// This Source Code Form is subject to the terms of the MIT License.
// If a copy of the MIT was not distributed with this file, You can obtain one at https://opensource.org/licenses/MIT.
// Copyright (C) Leszek Pomianowski and WPF UI Contributors.
// All Rights Reserved.

namespace Wpf.Ui.Gallery.Models.Monaco;

public enum MonacoLanguage
{
    Abap,
    Apex,
    Azcli,
    Bat,
    Bicep,
    Cameligo,
    Clojure,
    Coffee,
    Cpp,
    Csharp,
    Csp,
    Css,
    Cypher,
    Dart,
    Dockerfile,
    Ecl,
    Elixir,
    Flow9,
    FreeMarker2,
    Fsharp,
    Go,
    GraphQl,
    Hadnlebars,
    Hcl,
    Html,
    Ini,
    Java,
    JavaScript,
    Julia,
    Kotlin,
    Less,
    Lexon,
    Liquid,
    Lua,
    M3,
    Markdown,
    Mips,
    Msdax,
    MySql,
    ObjectiveC, // Objective-C,
    Pascal,
    PascaliGo,
    Perl,
    Pgsql,
    Php,
    Pla,
    Postiats,
    PowerQuery,
    Powershell,
    ProtoBuf,
    Pug,
    Python,
    Qsharp,
    R,
    Razor,
    Redis,
    Redshift,
    RestructuredText,
    Ruby,
    Rust,
    Sb,
    Scala,
    Scheme,
    Scss,
    Shell,
    Solidity,
    Sophia,
    Sparql,
    Sql,
    St,
    Swift,
    SystemVeriLog,
    Tcl,
    Twig,
    TypeScript,
    Vb,
    Xml,
    Yaml,
}
